### ISSUE TITLE
DRUMKNOTT_PAGES=y also indexes css, sourcemaps, etc.

### ISSUE THREAD

**Issue by halfbyte** [pat/drumknott#1]
Jekyll's `site.pages` iterates over all files within the Jekyll universe, including, for example, css files, sourcemaps, any feeds etc. - This is probably not desirable.

I think what we want is to iterate over `site.html_pages`?

I found this while debugging why drumknott borked after upgrading jekyll and specifically a new version of the sass plugin which started to build sourcemaps by default which drumknott choked on because of non ascii characters. There may be a character encoding handling bug in there as well, but the main issue is that drumknott tries to ingest the sourcemap file which is quite certainly not what I want.

I think I also would like a per-page option to skip indexing, but that's for another time.

If @pat agrees that using `site.html_pages` would make sense, I can do a PR for that.

**Comment by halfbyte** [comment]
I just realised that `site.html_pages` is available as a variable in templates but not as a method on the actual Jekyll:Site object Drumknott uses. This probably means one would need to duplicate the code at [lib/jekyll/drops/site_drop.rb](https://github.com/jekyll/jekyll/blob/d4e2d19d7e3814cb25dcd56c9d5165e2309e4613/lib/jekyll/drops/site_drop.rb#L31) to make this work.

**Comment by pat** [comment]
Such a change definitely makes sense to me - even if we need to duplicate that method. If you've the spare time to make it happen, that'd be great! Otherwise I can try to look into it next month :)

**Comment by pat** [comment]
Just published your fix in v0.4.0 :)

**Comment by halfbyte** [comment]
:tada: Thanks for the quick action!
